In [1]:
import numpy as np

x = [3, 1, 4, 1, 5, 9]
y = [2, 3, 0, 5, 1, 0]

print('mean of x    ', np.mean(x))
print('argmax of y', np.argmax(y))

mean of x     3.8333333333333335
argmax of y 3


In [3]:
x = np.array(x)
y = np.array(y)
print('x =', x)
print('y =', y)
print(type(x))

x = [3 1 4 1 5 9]
y = [2 3 0 5 1 0]
<class 'numpy.ndarray'>


In [4]:
print('x + y =', x + y)
print('2 * x =', 2 * x)

x + y = [5 4 4 6 6 9]
2 * x = [ 6  2  8  2 10 18]


In [5]:
print('x > 2 =', x > 2)
print('x ** 2 =', x ** 2)

x > 2 = [ True False  True False  True  True]
x ** 2 = [ 9  1 16  1 25 81]


In [7]:
import numpy as np 
import timeit

N = 1_000_000
xs_list = list(range(N))
xs_np   = np.arange(N)

t1 = timeit.timeit("[x*x for x in xs_list]", globals=globals(), number = 1)
t2 = timeit.timeit("xs_np ** 2",             globals=globals(), number=1)

print(f"리스트 컴프리헨션: {t1*1000:7.1f} ms")
print(f"numpy 벡터화    : {t2*1000:7.1f} ms")
print(f"속도 비         : {t1/t2:.1f}배")

리스트 컴프리헨션:    69.9 ms
numpy 벡터화    :     0.6 ms
속도 비         : 116.7배


In [7]:
import numpy as np

print(np.zeros((2, 4, 3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [14]:
print(np.empty((2, 3)))

[[ 1.79769313e+308 -1.79769313e+308  2.00000000e+000]
 [ 2.22044605e-016  2.22507386e-308  4.94065646e-324]]


In [17]:
c = np.array([1, 0, 2, 0, 3])
print(c.astype(bool))

[ True False  True False  True]


In [ ]:
# np.arange = range()의 numpy 버전 

a = np.arange(2 * 4 * 3)
print(type(a))
print(a)
print(range(24))

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
range(0, 24)


In [26]:
np.random.seed(1055)   # seed 고정 → 재현 가능 
a = np.arange(24)
np.random.shuffle(a)   # 제자리에서 섞기 
A = a.reshape((2, 4, 3))
print(A)

[[[15 16 13]
  [ 9  5  0]
  [ 3  4 12]
  [22  1 20]]

 [[21 19 11]
  [17 14  7]
  [ 2  6  8]
  [18 23 10]]]


In [ ]:
# 벡터 인덱싱 / 슬라이싱

print(A[0, :, 2])

[13  0 12 20]


In [34]:
# 불 인덱싱: 조건식

scores = np.array([88, 72, 95, 60, 81, 77, 90])

print(scores >= 80)         # 불 배열
print(scores[scores>=80])   # 필터링 (80점 이상만)

print(scores[(scores >= 70) & (scores < 90)])


[ True False  True False  True False  True]
[88 95 81 90]
[88 72 81 77]


In [43]:
# 팬시 인덱싱 

names = np.array(['강은수', '조재영', '이한솔', '뽀로로'])

print(names[[0, 3]])
print(names[[3, 0, 3, 0]])

['강은수' '뽀로로']
['뽀로로' '강은수' '뽀로로' '강은수']


In [44]:
# 팬시 인덱싱 활용

names = np.array(['강은수', '조재영', '이한솔', '뽀로로'])
scores = np.array([88, 72, 95, 60])

order = scores.argsort()
print(order)
print(names[order])
print(names[order][::-1])

[3 1 0 2]
['뽀로로' '조재영' '강은수' '이한솔']
['이한솔' '강은수' '조재영' '뽀로로']


In [ ]:
# 다차원 팬시 인덱싱

a = np.arange(10)
a[[1, 3, 5]] = 0
print(a)            # 팬시 인덱싱은 복사본을 돌려줌

scores = np.array([88, 45, 95, 30, 77])
scores[scores < 60] = 60
print(scores)

[0 0 2 0 4 0 6 7 8 9]
[88 60 95 60 77]


In [ ]:
A = np.random.seed(1055)    
print(A.max())

AttributeError: 'NoneType' object has no attribute 'max'